---
name: kwordquiz
version: 17.08.1
summary: A flashcard and vocabulary learning program
description: KWordQuiz is a general purpose flash card program. It can be used for
    vocabulary learning and many other subjects. It provides an editor and five different
    flashcard quiz modes. It uses the KVTML file format and contributed files can
    be downloaded from within the application.
confinement: strict
grade: stable
apps:
    kwordquiz:
        command: kf5-launch kwordquiz
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kwordquiz
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kwordquiz:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libkeduvocdocument-dev
        - libkf5kdelibs4support-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kwordquiz-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
